project: 
  type: website
  output-dir: "." 

website:
  title: "YOUR NAME"
  navbar:
    # background: "#1c4982"
    pinned: true
    left:
      - text: Blog
        href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub, Quarto, and Jupyter Notebook<br>Â© YOUR NAME, 2025"

format:
  html:
    theme: 
      light: flatly # flatly sandstone yeti united litera journal
      dark: darkly #  darkly cyborg slate solra superhero
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
    toc: false
    include-after-body: target_blank.html

